Repository hoprnet/hopr-core-ethereum, pull requests merged in 2020-08, with the labels that each got.

#80 Bump node versions
  .github/workflows/nodejs.yml
  lib/channel/ticket.js
  package.json
  yarn.lock
Labels: Patch Version, merge when passing

#82 Use workflow from hopr-workflow@0e1c862
  .github/workflows/build-test-and-release.yaml
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
Labels: Patch Version

#87 Minor fixes
  .github/workflows/build-test-and-release.yaml
  package.json
  src/channel/index.spec.ts
  src/hashedSecret.spec.ts
  yarn.lock
Labels: Minor Version

#88 Minor fixes
  .github/workflows/build-test-and-release.yaml
Labels: Patch Version

#90 Version bump
  .gitignore
  package.json
  scripts/build.sh
  yarn.lock
Labels: Patch Version

#92 enforce proper typings
  src/types/accountId.ts
  src/types/channel.ts
  src/types/channelBalance.ts
  src/types/channelEntry.ts
  src/types/public.ts
  src/types/signedChannel.ts
  src/types/solidity/bytes32.ts
  src/types/solidity/uint256.ts
  src/types/ticket.ts
  src/utils/index.ts
Labels: Patch Version

#94 Feature/upgrade path selection api
  package.json
  src/path/index.spec.ts
  src/path/index.ts
  yarn.lock
Labels: Patch Version

#100 🎨 change log message
  src/index.ts
Labels: Minor Version
